import Head from "next/head";
import { RoverFeed } from "../components/RoverFeed";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Spacestagram: Image-sharing from the final frontier</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Spacestagram</h1>
        <h2>Image-sharing from the final frontier</h2>
        <RoverFeed />
      </main>

      <footer className={styles.footer}>By Aiden Kerr</footer>
    </div>
  );
}
